### PR TITLE
Allow `make gen-arm` to be rerun by deleting the generated code

### PR DESCRIPTION
**Pull request by babbageclunk**
Since the generated code doesn't currently build it would prevent `make gen-arm` from being rerun until the apis directory was removed.

Fix a bug in codegen.isFileGenerated that would fail to close files (so the cleanup code would die with "too many open files" - move the deferred close to before the early return.

### CODE REVIEW

**Review by theunrepentantgeek — APPROVED** [review]
👍

**Comment by matthchr** [comment]
@babbageclunk it looks like this breaks the `make manifests` section of the makefile.
I checked out your branch and poked around and even if we fix up the paths for that command (using `../apis` and `../config/crd/bases`) the `controller-gen` tool fails with:

>Error: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags ignore_autogenerated -- ../apis/...]: exit status 1: go: pattern ../apis/... refers to dir /home/matthchr/work/github/k8s-infra/hack/apis, outside module root /home/matthchr/work/github/k8s-infra/hack/generator


That error makes sense (to me) -- we can't place the code outside of a go module, and our go module roots at hack/generator. There's another go module up at the root of the repo...

I tried moving the generated code to the root module (`apis` folder at the root of the repo) and it will correctly generate the code there. I was able to get `make manifests` to work out of there too but there are other issues with putting the generated code there (mostly that's where the handcrafted code is and I am not sure that we're ready to colocate just yet, plus we can't just .gitignore those folders because that's where David Justice is crafted stuff).

It might be easiest to just add a hacky clean step that nukes the whole `apis` directory for now and leave a comment in the makefile that it should be removed as soon as we can.

Additionally, the problem (that the generated code doesn't build), probably needs to be root caused and fixed. It's going to have to actually build eventually, and most of the errors seem solvable (to me at least).

**Comment by matthchr** [comment]
I quickly went and categorized the build errors... here are the ones I see:
```
161 hits of "missing method DeepCopyObject" (on various types).
45 hits of "imported and not used: "k8s.io/apimachinery/pkg/apis/meta/v1" as metav1"
22 hits "redeclared in this block"
4 hits "too many errors" (not sure what THAT means...)
3 hits "cannot convert <true or false> (untyped string constant)"
```

**Comment by theunrepentantgeek** [comment]
> `45 hits of "imported and not used: "k8s.io/apimachinery/pkg/apis/meta/v1" as metav1"`

I don't think we need to worry about these ones; we import that everywhere but only have a few dozen errors, so I think the code reformatting pass we do when writing the files is mostly removing the unused references. Once we fix the other errors we should be good.

> `22 hits "redeclared in this block"` 

These intrigue me, are we duplicating things or is the duplication in the original schema? And, more importantly, what do we do about it?

**Comment by babbageclunk** [comment]
Yeah, I agree that we don't want to move the output of the generator up into the containing module yet. It doesn't make sense to build the generated code as part of building and running the generator (particularly if a bug in the generator means that we're producing invalid code as output), so it seems like the target should be outside this module. Maybe this would all be simplified if this module wasn't nested inside k8s-infra? (Sorry if this is an old settled argument.) 
For now I'm going to just delete the apis directory before generating again.

**Comment by theunrepentantgeek** [comment]
I think the duplicate outputs are because we're failing to dedupe the set of things we output; will confirm that and fix (if so).

**Pull request merged**
